### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by iRachelxo** [learn-co-curriculum/welcome-completing-assignments#14]
Towards the bottom of the Introduction section there is the following: 

"Note: In order to work on and submit assignments, you will need to connect your GitHub account to your Learn.co account. For more information on this, check out **this help article**" <-- This link doesn't work

**Comment by AlveeM** [comment]
Hello, and thank you for submitting this issue.

It seems the broken link has been fixed since you submitted this issue. Here's [the repo](https://github.com/learn-co-curriculum/phase-0-configuring-the-flatiron-student-portal) it's linking to now.

We apologize for any frustration you might have encountered. Thank you for pointing out the issue. We really appreciate your help in improving our curriculum!
